// DO NOT EDIT: This file is autogenerated via the builtin command.

package functions

import (
	_ "github.com/influxdata/flux/functions/influxdb"
	_ "github.com/influxdata/flux/functions/influxdb/telegraf"
	_ "github.com/influxdata/flux/functions/testing"
	_ "github.com/influxdata/flux/functions/tests/testdata"
)
