// DO NOT EDIT: This file is autogenerated via the builtin command.

package stdlib

import (
	ast "github.com/wolffcm/flux/ast"
	date "github.com/wolffcm/flux/stdlib/date"
	experimental "github.com/wolffcm/flux/stdlib/experimental"
	aggregate "github.com/wolffcm/flux/stdlib/experimental/aggregate"
	geo "github.com/wolffcm/flux/stdlib/experimental/geo"
	http "github.com/wolffcm/flux/stdlib/http"
	monitor "github.com/wolffcm/flux/stdlib/influxdata/influxdb/monitor"
	secrets "github.com/wolffcm/flux/stdlib/influxdata/influxdb/secrets"
	v1 "github.com/wolffcm/flux/stdlib/influxdata/influxdb/v1"
	promql "github.com/wolffcm/flux/stdlib/internal/promql"
	regexp "github.com/wolffcm/flux/stdlib/regexp"
	strings "github.com/wolffcm/flux/stdlib/strings"
	chronograf "github.com/wolffcm/flux/stdlib/testing/chronograf"
	influxql "github.com/wolffcm/flux/stdlib/testing/influxql"
	kapacitor "github.com/wolffcm/flux/stdlib/testing/kapacitor"
	pandas "github.com/wolffcm/flux/stdlib/testing/pandas"
	prometheus "github.com/wolffcm/flux/stdlib/testing/prometheus"
	promql1 "github.com/wolffcm/flux/stdlib/testing/promql"
	usage "github.com/wolffcm/flux/stdlib/testing/usage"
	universe "github.com/wolffcm/flux/stdlib/universe"
)

var FluxTestPackages = func() []*ast.Package {
	var pkgs []*ast.Package
	pkgs = append(pkgs, date.FluxTestPackages...)
	pkgs = append(pkgs, experimental.FluxTestPackages...)
	pkgs = append(pkgs, aggregate.FluxTestPackages...)
	pkgs = append(pkgs, geo.FluxTestPackages...)
	pkgs = append(pkgs, http.FluxTestPackages...)
	pkgs = append(pkgs, monitor.FluxTestPackages...)
	pkgs = append(pkgs, secrets.FluxTestPackages...)
	pkgs = append(pkgs, v1.FluxTestPackages...)
	pkgs = append(pkgs, promql.FluxTestPackages...)
	pkgs = append(pkgs, regexp.FluxTestPackages...)
	pkgs = append(pkgs, strings.FluxTestPackages...)
	pkgs = append(pkgs, chronograf.FluxTestPackages...)
	pkgs = append(pkgs, influxql.FluxTestPackages...)
	pkgs = append(pkgs, kapacitor.FluxTestPackages...)
	pkgs = append(pkgs, pandas.FluxTestPackages...)
	pkgs = append(pkgs, prometheus.FluxTestPackages...)
	pkgs = append(pkgs, promql1.FluxTestPackages...)
	pkgs = append(pkgs, usage.FluxTestPackages...)
	pkgs = append(pkgs, universe.FluxTestPackages...)
	return pkgs
}()
